version: "3.6"
services:
  web:
    image: 'gitlab/gitlab-ce'
    container_name: 'gitlab'
    restart: always
    hostname: my.gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://my.gitlab:9090'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    networks:
      - gitlab-network
    ports:
      - '9080:80'
      - '7443:443'
      - '9090:9090'
      - '2224:22'
networks:
  gitlab-network:
    name: gitlab-network